//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trying01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public int id_task { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public System.DateTime time_start { get; set; }
        public System.DateTime time_finish { get; set; }
        public string login { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
